title: inxware-lucid Community
description: inxware-lucid is a universal no-code software development platform.
show_downloads: true
google_analytics:
sidebar: 
- label: Section One
    - document-home
    children:
      - document-one
      - document-two
      - document-three
